services:
    db:
        image: postgres:16
        container_name: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: altametrics
        ports:
            - "5432:5432"
        networks:
            - app-network

volumes:
    pgdata:


networks:
    app-network:
        driver: bridge
